### ISSUE TITLE
Client generator should handle unsupported message types more gracefully

### ISSUE THREAD

**Issue by bkeryan** [ni/measurement-plugin-python#974]
# Bug Report

The client generator does not support https://github.com/ni/ni-apis/blob/main/ni/protobuf/types/waveform.proto yet. If you try to generate a client for a plugin that uses DoubleAnalogWaveform, you get a couple of misleading low-level errors.

Also, when using `--all`, this terminates code generation early, so it might not get to all of the other services.

## Repro or Code Sample

Run ASW internal build of InstrumentStudio, then run `ni-measurement-plugin-generator --all`

## Expected Behavior

`--all` skips `ni.examples.WaveformMeasurement_NET`  and prints a warning that this plug-in was skipped because it uses `ni.protobuf.types.DoubleAnalogWaveform`, which is not supported.

`-s ni.examples.WaveformMeasurement_NET` does the same, but it's an error instead of a warning.

## Current Behavior
```(.venv) PS D:\dev\measurement-plugin-python\examples\client> ni-measurement-plugin-client-generator --all
The measurement plug-in client for the service class 'ni.examples.EnumMeasurement' has been successfully created as 'enum_measurement_client.py'.
...
The measurement plug-in client for the service class 'ni.examples.UIProgressUpdates_NET' has been successfully created as 'ui_progress_updates_net_client.py'.
Traceback (most recent call last):
  File "D:\dev\measurement-plugin-python\examples\client\.venv\lib\site-packages\ni_measurement_plugin_sdk_service\_internal\parameter\serialization_descriptors.py", line 115, in create_file_descriptor
    pool.FindFileByName(service_name)
KeyError: "Couldn't find file ni.examples.WaveformMeasurement_NET"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.9.13\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.9.13\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\dev\measurement-plugin-python\examples\client\.venv\Scripts\ni-measurement-plugin-client-generator.exe\__main__.py", line 7, in <module>
  File "D:\dev\measurement-plugin-python\examples\client\.venv\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "D:\dev\measurement-plugin-python\examples\client\.venv\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "D:\dev\measurement-plugin-python\examples\client\.venv\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\dev\measurement-plugin-python\examples\client\.venv\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\dev\measurement-plugin-python\examples\client\.venv\lib\site-packages\ni_measurement_plugin_sdk_generator\client\__init__.py", line 279, in create_client
    _create_all_clients(directory_out)
  File "D:\dev\measurement-plugin-python\examples\client\.venv\lib\site-packages\ni_measurement_plugin_sdk_generator\client\__init__.py", line 126, in _create_all_clients
    _create_client(
  File "D:\dev\measurement-plugin-python\examples\client\.venv\lib\site-packages\ni_measurement_plugin_sdk_generator\client\__init__.py", line 72, in _create_client
    configuration_metadata, output_metadata = get_configuration_and_output_metadata_by_index(
  File "D:\dev\measurement-plugin-python\examples\client\.venv\lib\site-packages\ni_measurement_plugin_sdk_generator\client\_support.py", line 174, in get_configuration_and_output_metadata_by_index
    create_file_descriptor(
  File "D:\dev\measurement-plugin-python\examples\client\.venv\lib\site-packages\ni_measurement_plugin_sdk_service\_internal\parameter\serialization_descriptors.py", line 122, in create_file_descriptor
    pool.Add(file_descriptor)
TypeError: Couldn't build proto file into descriptor pool: couldn't resolve name 'ni.protobuf.types.DoubleAnalogWaveform'
```

## Context

Testing #966 

## Your Environment

* OS & Device: Windows
* `ni-measurement-plugin-sdk-service` version: 2.1.0 main
* MeasurementLink version: 25.0.0d71
* Python version: 3.9.13

[AB#2902947](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2902947)

**Comment by bkeryan** [comment]
Related: this error also terminates `--all`

```
The measurement plug-in client for the service class 'ni.examples.UIProgressUpdates_NET' has been successfully created as 'ui_progress_updates_client.py'.
Error: Measurement configuration with message datatype is not supported.
```
